# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TranslateTextHTMLTransliterateAutoDetectionApi")

api_instance <- TranslateTextHTMLTransliterateAutoDetectionApi$new()

test_that("TranslatePost", {
  # tests for TranslatePost
  # base path: https://api-b2b.backenster.com/b1/api/v3
  # Translate
  # This method translates text and HTML single string or arrays. Also it performs transliteration, language auto detection. Please, check request examples on the right to check these capabilities.
  # @param translate_post_request TranslatePostRequest  (optional)
  # @return [TranslatePost200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
