# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TranslatePost200Response")

model_instance <- TranslatePost200Response$new()

test_that("err", {
  # tests for the property `err` (character)
  # the text of the error. It is null if the response status is 200. Otherwise, it contains a string

  # uncomment below to test the property
  #expect_equal(model.instance$`err`, "EXPECTED_RESULT")
})

test_that("result", {
  # tests for the property `result` (TranslatePost200ResponseResult)

  # uncomment below to test the property
  #expect_equal(model.instance$`result`, "EXPECTED_RESULT")
})

test_that("sourceTransliteration", {
  # tests for the property `sourceTransliteration` (character)
  # return only if enableTransliteration request param is true. Transliteration of source data. In the event that a line was sent to the translation, the result is also a string; if an array of strings, then we also get an array of strings

  # uncomment below to test the property
  #expect_equal(model.instance$`sourceTransliteration`, "EXPECTED_RESULT")
})

test_that("targetTransliteration", {
  # tests for the property `targetTransliteration` (character)
  # return only if enableTransliteration request param is true. Transliteration results. In the event that a line was sent to the translation, the result is also a string; if an array of strings, then we also get an array of strings

  # uncomment below to test the property
  #expect_equal(model.instance$`targetTransliteration`, "EXPECTED_RESULT")
})
