# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuthError")

model_instance <- AuthError$new()

test_that("err", {
  # tests for the property `err` (character)
  # the text of the error. It is null if the response status is 200. Otherwise, it contains a string

  # uncomment below to test the property
  #expect_equal(model.instance$`err`, "EXPECTED_RESULT")
})
