# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TranslatePostRequest")

model_instance <- TranslatePostRequest$new()

test_that("from", {
  # tests for the property `from` (character)
  # the language code in the format “language code_code of the country” from which the text is translated. The language code is represented only in lowercase letters, the country code only in uppercase letters (example en_GB, es_ES, ru_RU and etc.). If this parameter is not present, the auto-detect language mode is enabled

  # uncomment below to test the property
  #expect_equal(model.instance$`from`, "EXPECTED_RESULT")
})

test_that("to", {
  # tests for the property `to` (character)
  # language code in the format “language code_code of the country” to which the text is translated (required)

  # uncomment below to test the property
  #expect_equal(model.instance$`to`, "EXPECTED_RESULT")
})

test_that("data", {
  # tests for the property `data` (TranslatePostRequestData)

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("translateMode", {
  # tests for the property `translateMode` (character)
  # Describe the input text format. Possible value is \&quot;html\&quot; for  translating and preserving html structure. If value is not  specified or is other than \&quot;html\&quot; than plain text is translating.  

  # uncomment below to test the property
  #expect_equal(model.instance$`translateMode`, "EXPECTED_RESULT")
})

test_that("enableTransliteration", {
  # tests for the property `enableTransliteration` (character)
  # If true response includes sourceTransliteration and targetTransliteration fields.           platform:

  # uncomment below to test the property
  #expect_equal(model.instance$`enableTransliteration`, "EXPECTED_RESULT")
})

test_that("platform", {
  # tests for the property `platform` (character)
  # api

  # uncomment below to test the property
  #expect_equal(model.instance$`platform`, "EXPECTED_RESULT")
})
