#' Lingvanex Cloud API
#'
#' Lingvanex works via HTTPS requests. The URL of all requests starts with https://api-b2b.backenster.com/b1/api/v3/. In case of a protocol selection error and using HTTP, the request will be redirected to the address with the HTTPS protocol (status code 302). <br><br>Authentication of requests is done by adding the “Authorization” header with the following data format: Bearer The key can be created on the user control panel page https://lingvanex.com/account. Example: \"Authorization: Bearer <YOUR_API_KEY>\".
#'
#' The version of the OpenAPI document: 1.0.0
#' Contact: info@lingvanex.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title GetLanguages operations
#' @description GetLanguagesApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ GetLanguagesGet } \emph{ Getting the list of languages }
#'
#' \itemize{
#' \item \emph{ @param } platform character
#' \item \emph{ @param } code character
#' \item \emph{ @returnType } \link{GetLanguagesGet200Response} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : GetLanguagesGet200Response
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Authorization error. You should add the API_KEY to request which can be created on the user control panel page https://lingvanex.com/account
#'
#' \item return type : AuthError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  GetLanguagesGet  ####################
#'
#' library(openapi)
#' var_platform <- "api" # character | api
#' var_code <- "en_GB" # character | the language code in the format “language code_code of the country”, which is used to display the names of the languages. The language code is represented only in lowercase letters, the country code only in uppercase letters (example en_GB, es_ES, ru_RU etc). If this option is not present, then English is used by default (Optional)
#'
#' #Getting the list of languages
#' api_instance <- GetLanguagesApi$new()
#'
#' # Configure API key authorization: APIKeyHeader
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GetLanguagesGet(var_platform, code = var_codedata_file = "result.txt")
#' result <- api_instance$GetLanguagesGet(var_platform, code = var_code)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
GetLanguagesApi <- R6::R6Class(
  "GetLanguagesApi",
  public = list(
    api_client = NULL,
    #' Initialize a new GetLanguagesApi.
    #'
    #' @description
    #' Initialize a new GetLanguagesApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Getting the list of languages
    #'
    #' @description
    #' Getting the list of languages
    #'
    #' @param platform api
    #' @param code (optional) the language code in the format “language code_code of the country”, which is used to display the names of the languages. The language code is represented only in lowercase letters, the country code only in uppercase letters (example en_GB, es_ES, ru_RU etc). If this option is not present, then English is used by default (default value: "en_GB")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return GetLanguagesGet200Response
    #' @export
    GetLanguagesGet = function(platform, code = "en_GB", data_file = NULL, ...) {
      local_var_response <- self$GetLanguagesGetWithHttpInfo(platform, code, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Getting the list of languages
    #'
    #' @description
    #' Getting the list of languages
    #'
    #' @param platform api
    #' @param code (optional) the language code in the format “language code_code of the country”, which is used to display the names of the languages. The language code is represented only in lowercase letters, the country code only in uppercase letters (example en_GB, es_ES, ru_RU etc). If this option is not present, then English is used by default (default value: "en_GB")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (GetLanguagesGet200Response) with additional information such as HTTP status code, headers
    #' @export
    GetLanguagesGetWithHttpInfo = function(platform, code = "en_GB", data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`platform`)) {
        stop("Missing required parameter `platform`.")
      }



      query_params[["platform"]] <- `platform`

      query_params[["code"]] <- `code`

      local_var_url_path <- "/getLanguages"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "GetLanguagesGet200Response", loadNamespace("openapi")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
