#' Lingvanex Cloud API
#'
#' Lingvanex works via HTTPS requests. The URL of all requests starts with https://api-b2b.backenster.com/b1/api/v3/. In case of a protocol selection error and using HTTP, the request will be redirected to the address with the HTTPS protocol (status code 302). <br><br>Authentication of requests is done by adding the “Authorization” header with the following data format: Bearer The key can be created on the user control panel page https://lingvanex.com/account. Example: \"Authorization: Bearer <YOUR_API_KEY>\".
#'
#' The version of the OpenAPI document: 1.0.0
#' Contact: info@lingvanex.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title TranslateTextHTMLTransliterateAutoDetection operations
#' @description TranslateTextHTMLTransliterateAutoDetectionApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ TranslatePost } \emph{ Translate }
#' This method translates text and HTML single string or arrays. Also it performs transliteration, language auto detection. Please, check request examples on the right to check these capabilities.
#'
#' \itemize{
#' \item \emph{ @param } translate_post_request \link{TranslatePostRequest}
#' \item \emph{ @returnType } \link{TranslatePost200Response} \cr
#'
#'
#' \item status code : 200 | success
#'
#' \item return type : TranslatePost200Response
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Authorization error. You should add the API_KEY to request which can be created on the user control panel page https://lingvanex.com/account
#'
#' \item return type : AuthError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  TranslatePost  ####################
#'
#' library(openapi)
#' var_translate_post_request <- _translate_post_request$new("to_example", _translate_post_request_data$new(), "platform_example", "from_example", "html", "enableTransliteration_example") # TranslatePostRequest |  (Optional)
#'
#' #Translate
#' api_instance <- TranslateTextHTMLTransliterateAutoDetectionApi$new()
#'
#' # Configure API key authorization: APIKeyHeader
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$TranslatePost(translate_post_request = var_translate_post_requestdata_file = "result.txt")
#' result <- api_instance$TranslatePost(translate_post_request = var_translate_post_request)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
TranslateTextHTMLTransliterateAutoDetectionApi <- R6::R6Class(
  "TranslateTextHTMLTransliterateAutoDetectionApi",
  public = list(
    api_client = NULL,
    #' Initialize a new TranslateTextHTMLTransliterateAutoDetectionApi.
    #'
    #' @description
    #' Initialize a new TranslateTextHTMLTransliterateAutoDetectionApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Translate
    #'
    #' @description
    #' Translate
    #'
    #' @param translate_post_request (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return TranslatePost200Response
    #' @export
    TranslatePost = function(translate_post_request = NULL, data_file = NULL, ...) {
      local_var_response <- self$TranslatePostWithHttpInfo(translate_post_request, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Translate
    #'
    #' @description
    #' Translate
    #'
    #' @param translate_post_request (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (TranslatePost200Response) with additional information such as HTTP status code, headers
    #' @export
    TranslatePostWithHttpInfo = function(translate_post_request = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE


      if (!is.null(`translate_post_request`)) {
        local_var_body <- `translate_post_request`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/translate"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "TranslatePost200Response", loadNamespace("openapi")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
